### ISSUE TITLE
Re-order front page content sections

### ISSUE THREAD

**Issue by lauren-johnston** [Representable/representable#130]
**Is your feature request related to a problem? Please describe.**
I think it would be helpful to rethink ordering of front page sections now that we've added new sections to follow a more logical flow.

**Describe the solution you'd like**
I don't have an idea for the solution yet.

**Additional context**
Here's a zoomed out view.
<img width="313" alt="Screen Shot 2020-05-24 at 4 19 27 PM" src="https://user-images.githubusercontent.com/8892509/82767188-73d52000-9dda-11ea-98e7-4291ec141578.png">

**Comment by theodormarcu** [comment]
I was initially thinking about making the map slightly smaller and adding it to the right instead of the nice graphic. We should prioritize for the user flow and conversions. However, we also must be mindful of the fact that we need to explain Representable.org to users as well.

**Comment by k-y-le** [comment]
I like the idea of moving the state map to the right so that the flow is more straightforward. I think if we make that change it would be helpful to add a bit more information to orient users under the initial tagline
