### ISSUE TITLE
Partner map not visible when user is not logged in

### ISSUE THREAD

**Issue by lauren-johnston** [Representable/representable#140]
**Describe the bug**
I get the error in the screenshot when not logged in and trying to access partner map.

**To Reproduce**
1. Go to a campaign map while not logged in.

**Expected behavior**
Partner map is visible without PI even when user is not logged in.

**Screenshots**
<img width="1185" alt="Screen Shot 2020-05-25 at 9 15 05 PM" src="https://user-images.githubusercontent.com/8892509/82859890-dc042e80-9ecc-11ea-8e98-53320d9223a4.png">

**Comment by k-y-le** [comment]
Good catch! I made the fix in my branch with front page changes -- will include in the PR tomorrow once we decide on content for that page
