### ISSUE TITLE
Remove/change inconsistent placeholders on entry section 3

### ISSUE THREAD

**Issue by lauren-johnston** [Representable/representable#165]
**Is your feature request related to a problem? Please describe.**
Low priority - placeholder text on section 3 does not match other section.

**Describe the solution you'd like**
Placeholder text can be changed to the same format as others. "..." can be removed.

<img width="924" alt="Screen Shot 2020-05-28 at 11 04 47 AM" src="https://user-images.githubusercontent.com/8892509/83177044-4686bb80-a0d3-11ea-8ddb-9bdeff906214.png">

**Comment by theodormarcu** [comment]
I think it's important to leave placeholder texts here because there is no "Show Examples" button.

**Comment by lauren-johnston** [comment]
> I think it's important to leave placeholder texts here because there is no "Show Examples" button.

Ok gonna suggest that we reformat "My local community..." to remove the "...".  We could make the placeholder "Community Name".

**Comment by theodormarcu** [comment]
Sounds good!

**Comment by theodormarcu** [comment]
Closed via #179
