### ISSUE TITLE
Customers (orgs) want to see if a user submitted through an organization.

### ISSUE THREAD

**Issue by theodormarcu** [Representable/representable#178]
Our partners are interested in adding a field for users to highlight their role in the organization that they're submitting info to.

**Describe the solution you'd like**
1. Better understand why this is necessary.
2. Add a field under community name:
"What is your role in the organization?"

**Additional Context:** 
See paper and pencil form.

**Comment by lauren-johnston** [comment]
@theodormarcu are we definitely including this in future work with MI partners? we can discuss friday

**Comment by k-y-le** [comment]
Closing for now as discussions landed on the idea that this isn't currently relevant
