### ISSUE TITLE
Replace privacy policy (r.org/privacy) with short privacy description.

### ISSUE THREAD

**Issue by lauren-johnston** [Representable/representable#191]
**Is your feature request related to a problem? Please describe.**
Privacy policy out of date.

**Describe the solution you'd like**
Replace privacy policy with: "Your privacy is our highest priority. We gather your personal information to verify that you are a real person. We will not share anyone's individual personal information or maps.” 

Also include a text that says "we will be updating this page soon" or something to that effect.

**Comment by theodormarcu** [comment]
I read our privacy policy again. While we should do this for now, I don't think we can get anything better than what we currently have.
