### ISSUE TITLE
[User feedback - cannot replicate] skipping identifying information wipes map page on submission

### ISSUE THREAD

**Issue by lauren-johnston** [Representable/representable#192]
**Describe the bug**
Feedback: " In one trial, we skipped the identifying information and just drew the map and then tried to save it. It threw us back to the identification section and wiped out the map."

**To Reproduce**
Cannot replicate on our end (user may have testing on an older version of website). Waiting for clarification.

**Comment by theodormarcu** [comment]
The user cannot replicate it anymore either. We should close this.
