### ISSUE TITLE
Bug: non-contiguous communities not saved properly in census block polygon

### ISSUE THREAD

**Issue by k-y-le** [Representable/representable#202]
**Describe the bug**
It is possible to draw a community that is contiguous as a drawn polygon, but not contiguous for the census blocks polygon. If this is the case, then the database only saves one of the census block polygons (inaccurate community) - see screenshots bc it's kinda hard to describe
**To Reproduce**
1. Draw a community like this
![image](https://user-images.githubusercontent.com/41943646/84346938-8af67900-abf4-11ea-82ef-37103710c660.png)
2. See the version in the db (just one part of the community)
![image](https://user-images.githubusercontent.com/41943646/84347015-d1e46e80-abf4-11ea-875a-4c1f10c0c2f7.png)
This is def an edge case so not high priority -- should probably check the contiguous nature of the census block polygon in validation 🌵

**Comment by lauren-johnston** [comment]
Closed via Kyle's PR.
