### ISSUE TITLE
Users need to be able to sign up for the website and verify their email then submit to a campaign without being redirected away from the campaign page.

### ISSUE THREAD

**Issue by lauren-johnston** [Representable/representable#234]
Context: Currently users are redirected away from the campaign page when they verify their email and come back to the website. We want to avoid losing people during the signup process.

**Comment by theodormarcu** [comment]
+100

*Theodor Marcu* | Princeton University | Computer Science | +1 (609) 933-5057 | theodormarcu.com ( http://theodormarcu.com )
