### ISSUE TITLE
Create state page template (like r.org/michigan but extensible for each state)

### ISSUE THREAD

**Issue by lauren-johnston** [Representable/representable#238]
Context:
We need a reusable template for state pages that corresponds with the state model (#237).

**Comment by lauren-johnston** [comment]
@k-y-le this could be a good thing for you + Olivia to collaborate on as an early content task? And Edward or Jessie could do the model/urls (#237). Needs to be scoped out more... but figured I'd add!

**Comment by k-y-le** [comment]
@lauren-johnston agree! and i have been wanting to update the michigan page design for a bit now.. 🕺

**Comment by lauren-johnston** [comment]
sweet! Also tagging #89 bc it's relevant.... could solve these two issues at the same time
