### ISSUE TITLE
Organizations want term "campaign" to be changed to "data collection" period or similar.

### ISSUE THREAD

**Issue by lauren-johnston** [Representable/representable#249]
Context:
Organizations have been confused by the word campaign and it would be helpful to change all references of it across the app.

**Comment by lauren-johnston** [comment]
@psiyer7 @okusio when's the best time for me to change this? knowing that it will affect content too

**Comment by okusio** [comment]
I can start inserting this into the state template-- as for the other materials we send out to partners, I think Preeti can give you a better answer

**Comment by psiyer7** [comment]
we'll hold off re-doing the viewing entries videos until this is done! new content (pitch deck) reflects this

**Comment by k-y-le** [comment]
As per our discussion in the PGP meeting today, we came to agreement on the term **community mapping drive**

Happy to discuss further but one consideration is that we want to stay away from the term _data_ for the most part

**Comment by lauren-johnston** [comment]
sounds good!
