### ISSUE TITLE
Maps should redraw if the user made a mistake in a form text field

### ISSUE THREAD

**Issue by theodormarcu** [Representable/representable#269]
**Describe the bug**
In some cases, when users submit a form without a required text field, the map does not redraw the community and highlight the right census block.

**To Reproduce**
1. Go to entry page.
2. Draw a map. 
3. Attempt to submit form without the address field.
4. Notice how the map is wiped.

**Expected behavior**
Map should always redraw if it was successfully drawn on form submission failed.

**Comment by lauren-johnston** [comment]
@k-y-le @ETedward is this still an issue or can we close this?

**Comment by k-y-le** [comment]
Closing this via #325
