### ISSUE TITLE
email verification

### ISSUE THREAD

**Issue by indraneel** [Representable/representable#27]
working on this in https://github.com/Representable/representable/tree/email-verification

**Comment by theodormarcu** [comment]
Hi! What is the status of this? We wanted to integrate it with the current updates.

**Comment by indraneel** [comment]
i haven't tested sending an email in production via sendgrid yet. is this a blocker for this release?

**Comment by theodormarcu** [comment]
Sort of. We want to have this feature so we can also implement password resets. Is the only problem that it wasn't pushed to Heroku?
