### ISSUE TITLE
Bug: [Unable to replicate - Memory Error] application error for user who submitted with campaign 

### ISSUE THREAD

**Issue by lauren-johnston** [Representable/representable#270]
**Describe the bug**

User submitted with User Testing Trial in MI. Received an application error on submit - we'll need to dig through heroku logs to find out what caused the server error. Current hypothesis: something to do with form submissions for users on allowlist or alternatively on thanks page.

User description: "after I submitted the entire "form" I received an error message: Application Error.
I had created an account that was verified."

**To Reproduce**
[Will update this when I am able to reproduce the issue]

**Expected behavior**
No application error, user should be redirected to correct page.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lauren-johnston** [comment]
- Tested this locally (made a user acct on allow list, then submitted to campaign), was unable to replicate an error 
- also tried submitting entry not through campaign - no error 
- Checked heroku logs - only saw "high memory usage" errors in the last 7 days, no app errors

Will dig into errors further

**Comment by lauren-johnston** [comment]
Second comment: realized this user was not in fact on the allowlist. Still not able to replicate error.

**Comment by lauren-johnston** [comment]
After digging through heroku logs, it seems that on 6/30 at 15:00 UTC the user joined, then about an hour and a half error we saw memory errors `Error R14 (Memory quota exceeded)`.

**Comment by theodormarcu** [comment]
Interesting. Do we know if the user drawing a really large map? I have issues when I try to draw bigger maps (the computer's fans start spinning out of control), which is linked to loading a lot of census blocks. The census blocks may be consuming a lot of memory after a while, which could trigger an application error in some cases. This would also explain another case that I saw and I couldn't diagnose.

I recommend we look into optimizing how we load census blocks. First, we should only load census blocks for a few states at a time. Secondly, we should query them async so the UX is not impacted.

*Theodor Marcu* | Princeton University | Computer Science | +1 (609) 933-5057 | theodormarcu.com ( http://theodormarcu.com )

**Comment by lauren-johnston** [comment]
@jessiejofielding and I just talked about optimizing how we save & load census blocks. Going to look into this in the next week! I think we should ask the user approximately the area of the census block. Maybe I can be in charge of following up with that.
