### ISSUE TITLE
Step by Step Guide

### ISSUE THREAD

**Issue by ETedward** [Representable/representable#289]
**Describe the bug**
The step by step guide to drawing the map deletes the user's map.

**To Reproduce**
1. Go to '/Entry/
2. Draw your community map
3. Click on the step by step guide, and go through the steps until you reach the "delete map" step
4. Observe that your community map is deleted

**Additional context**
User Interviews have also said that the step by step guide itself is confusing.
"When you see the step by step guide. First of all, it obscures the map. Second of all, the map jumps around so that you can't orient yourself when they're showing you buttons. The map is tucked around, so the button may be on the very edge of the mouth or other buttons. So be gone are part of the map. You can't get oriented. The map needs to sit still and the directions need to jump around with clear arrows to the buttons that are being talked about. So when I click on Next the map for the first step by step, the map moves up. So I'm only looking at the bottom half of the map." 

**Longterm Solution**
Potentially also consider replacing the step by step guide with a simple written guide on the side descriptions of the map controls and instructions on how to draw a map.

**Comment by k-y-le** [comment]
Closed via PR #345
