### ISSUE TITLE
Bug: Draw Polygon deletes User's Map

### ISSUE THREAD

**Issue by ETedward** [Representable/representable#290]
**Describe the bug**
The "draw polygon" button in map controls deletes a user's already drawn map. This occurs both after the user clicks on the "finish drawing" button and before.

**To Reproduce**
1. Go to the "/entry" page
2. Click on the "draw polygon" button, then draw a map of your community.
3. Click on the "draw polygon" button again.
4. Observe that your community map disappears.

**Expected behavior**
Your community map disappears after you click the "draw polygon" button. This should only be happening with "clear polygon"

**Comment by lauren-johnston** [comment]
I think this could be solved, similar to #291, with a popup. "this action will delete the current polygon and start a new one. Are you sure you want to delete your current polygon?"

**Comment by ETedward** [comment]
Agreed "are you sure you want to delete your current polygon?" will be very helpful! 
Although I think the "draw polygon" button simply shouldn't have the function of deleting a polygon, because that's already redundant in the "clear polygon" button?

**Comment by lauren-johnston** [comment]
We don't want them to draw multiple polygons though

**Comment by lauren-johnston** [comment]
I agree that would be weird if a popup to delete the current polygon popped up before you haven't started drawing the first time though

**Comment by k-y-le** [comment]
Closing as this depends on deprecated polygon tool
