### ISSUE TITLE
Bug: Clear polygon pressed accidentally due to proximity to edit polygon and finish drawing

### ISSUE THREAD

**Issue by lauren-johnston** [Representable/representable#291]
**Describe the bug**
I saw a user in MI trial accidentally click clear instead of edit.

**To Reproduce**
1. Go to entry page

**Expected behavior**
There should be an "are you sure you want to clear this polygon" popup. Related to #290 .

**Comment by ETedward** [comment]
Agreed! are you sure you want to clear might be helpful for clear polygon!

**Comment by lauren-johnston** [comment]
We also may not want to solve this immediately if we're considering moving away from polygon drawing tool - if we move to selection tool then we can have an eraser or something
