### ISSUE TITLE
turn off debug mode in production

### ISSUE THREAD

**Issue by indraneel** [Representable/representable#30]

**Comment by theodormarcu** [comment]
Debug mode (and other production/dev related settings) are automatically managed by the appropriate settings file. See representable/representable/settings

**Comment by theodormarcu** [comment]
Double-checked the prod file. You're right. It seems Andrew forgot to turn it off a long time ago when he contributed. I was not aware that this existed.

**Comment by theodormarcu** [comment]
Solved via #32
