### ISSUE TITLE
Users want more simple explanations of map units, rather than census blocks / blockgroups

### ISSUE THREAD

**Issue by k-y-le** [Representable/representable#301]
**Is your feature request related to a problem? Please describe.**
Users expressed confusion on what a census block/blockgroup is. They would benefit from a simpler explanation.

**Describe the solution you'd like**
When drawing the map, explain the process with something along the lines of "Draw your map by selecting units (census blockgroups) below." with a popup/accordion on clicking census blockgroups that explains what they are and why we use them.

**Comment by lauren-johnston** [comment]
Closed - fixed via PR.
