### ISSUE TITLE
Hover on entry page not working

### ISSUE THREAD

**Issue by k-y-le** [Representable/representable#352]
**Describe the bug**
When searching for a different state, the hover functionality on the entry page doesn't seem to work.

**To Reproduce**
1. Go to /entry
2. search for location (ex. detroit)
3. check that hover works
4. if working, search for a new location (ex. princeton)
5. check that hover works
(note: the second time trying to replicate this, hover wasn't working for the first place i tried, without searching a second time)

**Expected behavior**
Hover should highlight block groups

**Screenshots**

**Comment by lauren-johnston** [comment]
@k-y-le do we know which PR introduced this issue? thinking we should try to fix before deployment tonight

**Comment by k-y-le** [comment]
> @k-y-le do we know which PR introduced this issue? thinking we should try to fix before deployment tonight

I'm not sure, but i think it may be from #338
