### ISSUE TITLE
Bug: clicking drive link goes to page not found

### ISSUE THREAD

**Issue by ETedward** [Representable/representable#365]
**Describe the bug**
Link to the drive with /MI/ does not exist. See screenshots.
(on the other hand /drive/test does exist)

**Screenshots**
<img width="1132" alt="Screen Shot 2020-08-14 at 4 07 05 PM" src="https://user-images.githubusercontent.com/13109022/90288714-6e6efb00-de48-11ea-9521-fb6479f2cf3c.png">
<img width="395" alt="Screen Shot 2020-08-14 at 4 09 04 PM" src="https://user-images.githubusercontent.com/13109022/90288761-86467f00-de48-11ea-8be4-ee459eb557a2.png">

**Comment by lauren-johnston** [comment]
Thanks for opening this! The drive link should not have an /MI/ link,
right? We just want the drive itself and then the entry link has the state
code.
