### ISSUE TITLE
Add Civic Engagement Question

### ISSUE THREAD

**Issue by ETedward** [Representable/representable#379]
**Background.**
From user feedback and Oakland Forward's user trial:
People are not going to use this tool unless they feel they are making a difference.
Instead of jumping in to more technical questions like economic interests, Karmick from Oakland Forward strongly believes we should first be asking a question that provokes civic engagement. Two examples are provided below.

**Change**
Add a question on the entry page for users to answer that provokes civic engagement:
A. "Tell us about a time you felt heard or not heard by your government?"
B. "Do you feel fairly represented by your elected officials?"

**Comment by k-y-le** [comment]
closing this now as we've implemented this into the entry page redesign questions!
