### ISSUE TITLE
Entry page - Census blocks inside and outside of community same color 

### ISSUE THREAD

**Issue by lauren-johnston** [Representable/representable#42]
User feedback: "What is the lighter blue area to the west of my polygon and how can I get rid of it?" Replicated issue below with screenshot.

<img width="885" alt="Screen Shot 2020-05-05 at 10 16 56 PM" src="https://user-images.githubusercontent.com/8892509/81140473-50772d80-8f1e-11ea-93b8-bc8bbcb3a99e.png">

**Comment by k-y-le** [comment]
![image](https://user-images.githubusercontent.com/41943646/81167106-f76bd000-8fd7-11ea-9173-39068475baec.png)
they may have encountered something like this (unrelated to census blocks)
