### ISSUE TITLE
Organizations shouldn't be able to create a drive in a state the org doesn't operate in

### ISSUE THREAD

**Issue by k-y-le** [Representable/representable#428]
**Is your feature request related to a problem? Please describe.**
Currently, no matter what states an organization is within, they can select any state for a community drive

**Describe the solution you'd like**
Only allow organizations to select the state(s) they operate in when creating a community mapping drive

**Comment by arorasomya** [comment]
Chuk

**Comment by Chuk116** [comment]
Closing issue.
