### ISSUE TITLE
Users want an explanation of GeoJSON and why it matters when exporting

### ISSUE THREAD

**Issue by k-y-le** [Representable/representable#430]
**Is your feature request related to a problem? Please describe.**
Currently, there's very little guidance into what GeoJSON is and what to do with it
**Describe the solution you'd like**
After selecting "Export GeoJSON" on submission page, it automatically downloads, and a modal appears which briefly and clearly explains what GeoJSON is and how to use it with other mapping softwares / submit to a mapmaker.

**Comment by Denisqo** [comment]
I would like to work on this issue. Please assign me.

**Comment by arorasomya** [comment]
Jason
