### ISSUE TITLE
Remove zoom buttons on mobile maps

### ISSUE THREAD

**Issue by k-y-le** [Representable/representable#433]
**Is your feature request related to a problem? Please describe.**
Zoom buttons are not useful when one can pinch to zoom

**Describe the solution you'd like**
Zoom buttons are removed when being viewed on a phone / touch screen -- mapping apps like Google Maps don't have zoom buttons

**Comment by Denisqo** [comment]
I would like to work on this role. Please assign me

**Comment by arorasomya** [comment]
Chuk

**Comment by Chuk116** [comment]
Closing issue.
