### ISSUE TITLE
export entries

### ISSUE THREAD

**Issue by lauren-johnston** [Representable/representable#52]
Received feedback on 5/6/20 that exporting to shapefiles/geojson is crucial.

**Comment by indraneel** [comment]
To clarify, this was in reference to the ability to export to other mapping applications such as: ArcGIS, Maptitude, Dave's Redistricting App, etc. There isn't yet a lot of clarity around how much data will be shared and with whom it will be shared, so we'll have to revisit this later in 2020 as we get to that stage

The other separated but related issue here is #65
