### ISSUE TITLE
Add the educational video to the site

### ISSUE THREAD

**Issue by arorasomya** [Representable/representable#571]
**Is your feature request related to a problem? Please describe.**
Add the educational video to the site according to Olivia's design:

![image](https://user-images.githubusercontent.com/15281033/104051826-bfe0a380-51b6-11eb-9388-2fedf251249c.png)

Link to the video:
https://www.youtube.com/watch?v=vUbZoyCCR44&ab_channel=Representable

**Comment by json1016** [comment]
https://representable.org/entry_preview/

**Comment by json1016** [comment]
![image](https://user-images.githubusercontent.com/35666612/105058903-b7a12780-5a44-11eb-98ca-ba85f024dbbc.png)
