### ISSUE TITLE
Entry Page: Free Draw Tool (Not Polygons)

### ISSUE THREAD

**Issue by theodormarcu** [Representable/representable#58]
A few users mentioned that they want a tool like the one that can be used on Zillow. This would make it easier to draw borders around natural structures (e.g. lakes/parks/etc)
<img width="1511" alt="Screen Shot 2020-05-06 at 18 43 20" src="https://user-images.githubusercontent.com/8714338/81235784-bd93cd00-8fc9-11ea-897a-48f7340b3155.png">

**Comment by arorasomya** [comment]
I think it'll be harder to edit/work with the free drawing tool because you'll have to restart drawing, and you won't be able edit certain corners/vertices. It'll also create problems with zooming in/out of the map while drawing/ changing the position/pitch? Thoughts?

**Comment by lauren-johnston** [comment]
Closing this as we've decided not change the drawing tool.
