### ISSUE TITLE
Entry Page/Website: Clarify That Submitting Entry Does NOT Submit to Districting Commission

### ISSUE THREAD

**Issue by theodormarcu** [Representable/representable#59]
- We need to include a blurb at the end to encourage people to download/print their maps.
- Clarify that either them or the organizations need to submit the info to the commission.

**Comment by psiyer7** [comment]
**Other Clarifications that are needed Running List (@ various points):** 
2. When drawing -- your community might not look exactly how you drew it, it will snap to census blocks
3. When submitting -- Representable reserves the right to remove data based on moderation

**Comment by theodormarcu** [comment]
@k-y-le Can I take this? I might include some changes as well as part of new front end entry.

**Comment by k-y-le** [comment]
@theodormarcu yes feel free!

**Comment by theodormarcu** [comment]
Closing issue per PR.
