### ISSUE TITLE
Community tags not necessary

### ISSUE THREAD

**Issue by indraneel** [Representable/representable#68]
i know this is a team favorite, but I do think it is worth reconsidering given what we're hearing.

my sense is, if we really want to, we can implicitly generate tag-like info on the backend once we get responses

**Comment by lauren-johnston** [comment]
Yeah I think we should definitely discuss this tomorrow! ultimately we do need some way to provide aggregated community stats but I'm open to different ways we can do that

**Comment by k-y-le** [comment]
i think if we're adding more of the info from the paper form to the entries, then we don't necessarily need tags as much. the argument for keeping them in was that otherwise the only way to aggregate entries was based on name/reason, which is not much to work with

**Comment by theodormarcu** [comment]
Leaving this here for further consideration. Agree with Indraneels point. Once we have more data we can generate tags. For now we can just hide the field?

https://stackoverflow.com/questions/14339290/how-to-extract-keywords-tags-from-text
