### ISSUE TITLE
Improve organization/partner flow

### ISSUE THREAD

**Issue by arorasomya** [Representable/representable#88]
- Add another section on the front-page below state-selector for organizations. 
“Are you the leader of the organization?” 

- Add different coloring/signaling to showcase that it’s different from the user flow so normal users don’t get confused.
- Clarify that you’re only doing this if your organization is not here.
- Clarify that this is only for organization leaders.

**Comment by lauren-johnston** [comment]
I think @k-y-le 's front page changes cover this issue :)
